---
title: Mapping Sameness Identifier
subtitle: Version 0.0.0
date: today
# TODO
# doi: 10.5281/zenodo.XXXX
authors:
- name: Jakob Voß
  orcid: 0000-0002-7613-4123
  affiliations:
   - name: Verbundzentrale des GBV (VZG)
     ror: 048vdhs48
- name: Charles Tapley Hoyt
  orcid: 0000-0003-4423-4370
  affiliations:
   - name: RWTH Aachen University
     ror: 04xfq0f34
abstract: |
 This document specifies a content-based identifier for mappings.
---

# Introduction

Mappings (also known as **terminology mappings**, **correspondences**, or **semantic alignments**) are relevant to integrate and to compare data from diverse sources. If mappings are managed in distributed environments, there is a need to reference individual mappings with an identifier. Two kinds of identifiers exist:

- **Assigned identifiers** must explicitly be generated once by the source of a mapping and carried along with it.
- **Content-based identifiers** can be derived automatically from the content of a mapping.

This specification defines a content-based identifier for mappings. One use case is the distributed review of mappings: if some mapping is reviewed, the review should apply to other mappings with same content, independent from when, where, and by whom the mapping was created.

This specification consists of a definition of [mapping content](#mappings) and the definition of a method to [derive a mapping sameness identifier](#identifier) from the content. The method does not depend on any specific data format or programming language. The normative part of this specification is limited to [section 2](#definitions), [section 3](#identifier), and its references, excluding examples and notes. The appendix contains [examples](#examples) and [implementations](#implementations) for illustration.

# Definitions

## Terminology

The key words "MUST", "MUST NOT", "REQUIRED", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 ([RFC 2119] and [RFC 8174]) when, and only when, they appear in all capitals, as shown here.

## Mapping

A **mapping** is a 4-tuple of:

- **subjects**: a non-empty set of IRI
- **objects**: a non-empty set of IRI
- **predicate**: an absolute IRI, also known as mapping type
- **negativity**: either false for affirmative mappings or true for negative mappings

IRIs must be absolute as specificied in [RFC 3987]. IRIs SHOULD be based on NFC-normalized Unicode strings (see [RFC 3987] section 5.3.2.4).

A mapping is also called **1-to-1 mapping**, if both subjects and objects contain exactely one IRI each.

::: {.callout-tip title="Informative Notes"}
Applications may **restrict or extend mappings**, for instance by:

- limitation to 1-to-1-mappings
- limitation of the set of allowed predicates
- limitation to affirmative mappings
- allowing subjects and/or objects to be empty sets

Handling these models of mappings is out of the scope of this specification. The same applies to resolving different IRIs to one form if they refer to the same concept.

The definiton of a mapping roughly corresponds to a an edge in a **directed hypergraph**. The original use case of this specification was application to mappings between terminologies but there may be other uses in applications of directed hypergraphs such as chemical reaction networks and transport routing.
:::

::: {.callout-note title="Example 1: An affirmative 1-to-1 mapping"}
- subjects: `http://example.org/feline`
- objects: `http://example.com/cat`
- predicate: `http://www.w3.org/2002/07/owl#sameAs`
- negativity: `false`
:::
   
::: {.callout-note title="Example 2: A more complex mapping"}
- subjects: `http://example.org/red` and `http://example.org/blue`
- objects: `http://example.com/green`
- predicate: `http://www.w3.org/2004/02/skos/core#closeMatch`
- negativity: `true`
:::

# Identifier

A **mapping sameness identifier** is created from a Unicode string consisting of three elements, separated by space (U+0020):

1. mapping subjects sorted by Unicode Code Point and separated by vertical bar (U+007C)
2. mapping predicate
3. mapping objects sorted by Unicode Code Point and separated by vertical bar (U+007C)

The resulting string is encoded in UTF-8, then hashed with SHA-256 ([RFC 6234]), and the digest is serialized in hexadecimal form with lowercase letters. A tilde (`~`, U+007E) is prepended if the mapping is negative.

To use a mapping sameness identifier as IRI, the generated string is appended to URI namespace string `mapping:` (TODO: define an official namespace).

::: {.callout-warning}
Some programming languages, such as Python, sort strings by Unicode Code Points. JavaScript sorts by UTF-16 value instead. If IRIs don't include characters in the range U+010000 to U+10FFFF there is no difference. 
:::

::: {.callout-note title="Identifier of example 1"}
The string is `http://example.org/feline http://www.w3.org/2002/07/owl#sameAs http://example.com/cat`.

The mapping sameness identifier is `mapping:95a088082ab2b2a68638aebbcc3fe3e0f229da75a8b5bdbb9f3f8cd5e1e4286e`.
:::

::: {.callout-note title="Identifier of example 2"}
The string is `http://example.org/blue|http://example.org/red http://www.w3.org/2004/02/skos/core#closeMatch http://example.com/green`.

The mapping sameness identifier is `mapping:~424e7a86ea29d5a0aaf1d3d7da9a864b48121ac465c67163aef56f6f87bb1ba8` .
:::

# References

## Normative References

[RFC 2119]: https://tools.ietf.org/html/rfc2119
[RFC 3987]: https://tools.ietf.org/html/rfc3987
[RFC 4648]: https://tools.ietf.org/html/rfc4648
[RFC 6234]: https://tools.ietf.org/html/rfc6234
[RFC 8174]: https://tools.ietf.org/html/rfc8174

- Bradner, S.: _Key words for use in RFCs to Indicate Requirement Levels_.
  BCP 14, RFC 2119, March 1997,
  <http://www.rfc-editor.org/info/rfc2119>.
  
- Dürst, M. and Suignard, M.: _Internationalized Resource Identifiers (IRIs)_.
  RFC 3987, January 2005.
  <https://www.rfc-editor.org/info/rfc3987>.

- Eastlake D. and Hansen T.: _US Secure Hash Algorithms_.
  RFC 6234, May 2011.
  <https://www.rfc-editor.org/info/rfc2634>.

- Leiba, B.:  _Ambiguity of Uppercase vs Lowercase in RFC 2119 Key Words_.
  BCP 14, RFC 8174, May 2017,
  <http://www.rfc-editor.org/info/rfc8174>.
  
- Yergeau, F.: _UTF-8, a transformation format of ISO 10646._
  RFC 3629, November 2003. <https://tools.ietf.org/html/rfc3629>

## Informative references

- Bray, T.: _The JavaScript Object Notation (JSON) Data Interchange Format_.
  RFC 8259, December 2017. <https://tools.ietf.org/html/rfc8259>

- Matentzoglu, N., et al.: _A Simple Standard for Sharing Ontological Mappings (SSSOM)_.
  Database, Volume 2022, 2022, baac035, <https://doi.org/10.1093/database/baac035>

- Voß, J.: _JSKOS data format for Knowledge Organization Systems_.
  Version 0.7.1, January 2026. <https://gbv.github.io/jskos/>

# Appendix

The following information is non-normative.

## Examples {-}

### SSSOM {-}

Mappings can be expressed in the [Simple Standard for Sharing Ontological Mappings (SSSOM)](https://mapping-commons.github.io/sssom/)
in a tabular format:

~~~tsv
# curie_map:
#   ex: https://example.org
#   owl: http://www.w3.org/2002/07/owl#
#   semapv: https://w3id.org/semapv/vocab/
# mapping_set_id: https://example.org/example.sssom.tsv
subject_id	predicate_id	object_id	mapping_justification
ex:feline	owl:sameAs	ex:cat	semapv:UnspecifiedMatching
~~~

Negative mappings can be specified in SSSOM with the [`predicate_modifier`](https://w3id.org/sssom/predicate_modifier)
column:

~~~tsv
# curie_map:
#   ex: https://example.org
#   owl: http://www.w3.org/2002/07/owl#
#   semapv: https://w3id.org/semapv/vocab/
# mapping_set_id: https://example.org/example.sssom.tsv
subject_id	predicate_id	predicate_modifier	object_id	mapping_justification
ex:feline	owl:sameAs	Not	ex:dog	semapv:UnspecifiedMatching
~~~

### JSKOS {-}

Mappings can be expressed in [JSKOS data format](https://gbv.github.io/jskos/) with its [Mapping Object](https://gbv.github.io/jskos/#mapping):

~~~json
{
  "type": [
    "http://www.w3.org/2004/02/skos/core#mappingRelation",
    "http://www.w3.org/2002/07/owl#sameAs"
  ],
  "from": {
    "memberSet": [ { "uri": "http://example.org/feline" } ]
  },
  "to": {
    "memberSet": [ { "uri": "http://example.com/cat" } ]
  }
}
~~~

Note that in this example <http://www.w3.org/2004/02/skos/core#mappingRelation> does not encode the mapping predicate but the fact that this JSON object is a JSKOS mapping!

JSKOS supports mapping sources and mapping objects with multiple source but negative mappings are not supported yet (see [this issue](https://github.com/gbv/jskos/issues/173)). A negative mapping will likely be expressed like this:

~~~json
{
  "type": [
    false,
    "http://www.w3.org/2004/02/skos/core#closeMatch"
  ],
  "from": {
    "memberSet": [ 
      { "uri": "http://example.org/red" },
      { "uri": "http://example.org/blue" }
    ]
  },
  "to": {
    "memberSet": [ { "uri": "http://example.org/green" } ]
  }
}
~~~

### RDF {-}

A non-negative 1-to-1 mapping can be expressed in form of an RDF triple with mapping subjects being the RDF triple subject, mapping objects being the RDF triple object, and mapping predicate being the RDF triple predicate. An RDF triples can only represent a mappings if all of its elements are absolute IRIs.

For example mapping example 1 can be expressed in RDF Turtle syntax:

~~~ttl
<http://example.org/feline> <http://www.w3.org/2002/07/owl#sameAs> <http://example.com/cat> .
~~~

Expressing negative mappings and mappings beyond 1-to-1 mappings in RDF require more complex features and conventions such as reification or triple terms (also known as RDF-star, introduced in RDF 1.2). The choice of these features to express mappings is out of the scope of this document. The combination of mapping sameness identifiers and RDF statements to express mappings beyond non-negative 1-to-1 mappings is an anti-pattern:

~~~ttl
# Don't do this, it's a contradiction because the mapping is not negative:
<mapping:95a088082ab2b2a68638aebbcc3fe3e0f229da75a8b5bdbb9f3f8cd5e1e4286e> a ontology:NegativeMapping .
~~~

## Implementations {-}

The following scripts expect a JSON object with fields `subjects`, `predicate`, `objects`, and `negative` from standard input.

### Python {-}

~~~python
{{< include implementation/python.py >}}
~~~

### Command line tools {-}

~~~sh
{{< include implementation/cli.sh >}}
~~~

## Changes {-}

This document is managed in a revision control system at <https://github.com/ts4nfdi/mapping-sameness-identifier>, including an [issue tracker](https://github.com/ts4nfdi/mapping-sameness-identifier/issues).

- **Version 0.0.0**

  Working draft

## Acknowledgements {-}

Groundwork of this specification  was laid out at the second TS4NFDI Community Hands-On Workshop, March 2026 in Leipzig. We thank all participants and organizers.

